# This is a basic workflow to help you get started with Actions

name: Sanity URLs check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  schedule:
  - cron: "* * * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: http://links.esri.com/mapsforadobecc/winen
